### PR TITLE
Update Runtime to GNOME 42

### PR DESCRIPTION
**Pull request by Eonfge**
Also update the application

### CODE REVIEW

**Comment by Eonfge** [comment]
LGTM

**Comment by Eonfge** [comment]
@bilelmoussaoui Something you can tackle?

**Comment by tinywrkb** [comment]
Maybe use this chance to add f-e-d-c, add the missing dri device permission, add fallback-x11 socket.  
There are a bunch of other permissions [here](https://gitlab.gnome.org/GNOME/ghex/-/blob/master/org.gnome.GHex.Devel.json) to get gvfs work.  
Also, this doesn't seem to need any Gnome runtime specific lib, so I suggest switching to the annually updated Freedesktop runtime instead of the semi-annual updates of Gnome. This way, you cut the number of needed runtime bumps by half.

**Comment by tinywrkb** [comment]
Also, as a Gnome affiliated project, why isn't this being maintained by its developer.  
/ping @larathbone

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Something you can tackle?

I will go ahead and merge this. 



> Maybe use this chance to add f-e-d-c, add the missing dri device permission, add fallback-x11 socket. There are a bunch of other permissions [here](https://gitlab.gnome.org/GNOME/ghex/-/blob/master/org.gnome.GHex.Devel.json) to get gvfs to work. ~Also, this doesn't seem to need any Gnome runtime specific lib, so I suggest switching to the annually updated Freedesktop runtime instead of the semi-annual updates of Gnome. This way, you cut the number of needed runtime bumps by half.~ **edit:** v4 will switch to GTK4, and Freedesktop's maintainers have not plans to add the lib currently, so better stay on Gnome.

Feel free to submit new merge requests.

**Comment by larathbone** [comment]
I'm happy to take the reins on this -- the first stable release of ghex4 will be very soon (likely later in the week) and I maintain the json file for master as the upstream maintainer anyway, so I can keep this one up-to-date for the stable releases. Should I just send PR's as releases come out, or may I be granted direct write access to this repo?

**Pull request merged**
