### PR TITLE
Bump to 42.0, add f-e-d-c, flathub.json, and switch to tarball releases

### PR DESCRIPTION
**Pull request by tinywrkb**
Add f-e-d-c support using the Gnome checker, which generates tarball source links.
The benefits of archive type source are that there's no need for network on rebuilds,
and the build process starts faster.
Add flathub.json to disable auto-merging PRs create by flathubbot.

Waiting on flathub/flatpak-external-data-checker#284

### CODE REVIEW

**Comment by tinywrkb** [comment]
Rebased.  
The f-e-d-c issue with the Gnome checker was fixed, and `org.flathub.flatpak-external-data-checker` was updated.  
Also use this chance to bump to the latest release.

Ready for merge.

**Comment by tinywrkb** [comment]
bot, build org.gnome.GHex

**Comment by larathbone** [comment]
I'm good with these changes as compared to my conflicting version bump to 42.0. I simply preserved the -Dbuildtype=release from my prior commit and resolved the conflict, so we can be on our merry way. Thanks for this.

**Comment by tinywrkb** [comment]
Thanks for merging!

**Pull request merged**
